# Generated by Django 3.2.13 on 2022-07-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('headquarters', models.CharField(max_length=150)),
                ('company_email', models.EmailField(max_length=254)),
                ('twitter', models.URLField(max_length=1000, unique=True)),
                ('linkedln', models.CharField(max_length=1000, unique=True)),
                ('company_website', models.URLField(max_length=1000, unique=True)),
                ('net_worth', models.CharField(max_length=100)),
                ('area_served', models.CharField(max_length=25)),
                ('founders', models.CharField(max_length=200)),
                ('founded', models.DateField()),
                ('revenue', models.CharField(blank=True, max_length=150)),
                ('taxpayer_identification_number', models.IntegerField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
